### PR TITLE
Update assets to 0.6.16 & Bump version to 0.6.16.0

### PR DESCRIPTION
**Pull request by samrayner**

### CODE REVIEW

**Comment by seapy** [comment]
Good ~ i will check it

**Comment by seapy** [comment]
@samrayner Thanks for PR
but has a some issue
- specialchar plugin is not included summernote release.(https://github.com/summernote/summernote/releases/tag/v0.6.16)
- unnecessary mode change
```
mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ar-AR.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/bg-BG.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ca-ES.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/cs-CZ.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/da-DK.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/de-DE.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/es-ES.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/es-EU.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/fa-IR.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/fi-FI.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/fr-FR.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/he-IL.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/hu-HU.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/id-ID.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/it-IT.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ja-JP.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ko-KR.js
 create mode 100755 vendor/assets/javascripts/summernote/locales/lt-LT.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/nb-NO.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/nl-NL.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/pl-PL.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/pt-BR.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/pt-PT.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ro-RO.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/ru-RU.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/sk-SK.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/sl-SI.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/sr-RS-Latin.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/sr-RS.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/sv-SE.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/th-TH.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/tr-TR.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/uk-UA.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/vi-VN.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/zh-CN.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/locales/zh-TW.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/plugin/summernote-ext-hello.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/plugin/summernote-ext-hint.js
 create mode 100755 vendor/assets/javascripts/summernote/plugin/summernote-ext-specialchar.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/plugin/summernote-ext-video.js
 mode change 100644 => 100755 vendor/assets/javascripts/summernote/summernote.js
 mode change 100644 => 100755 vendor/assets/stylesheets/summernote.css
```

**Comment by samrayner** [comment]
Amended, thanks @seapy

**Comment by seapy** [comment]
Great! :+1: 
here is new version ~
https://rubygems.org/gems/summernote-rails/versions/0.6.16.0

**Comment by samrayner** [comment]
Thanks!

**Comment by luciuschoi** [comment]
great, fantastic!

**Pull request merged**
