### PR TITLE
Bump up 0.8.3

### PR DESCRIPTION
**Pull request by rsamoilov**

### CODE REVIEW

**Comment by hackerwins** [comment]
@rsamoilov Thanks for contribution.

**Comment by rsamoilov** [comment]
@hackerwins  Could you please push the new version to rubygems?

**Comment by riseshia** [comment]
@rsamoilov sorry, I'm late OTL. I pushed gem yesterday, so please check!

**Comment by rsamoilov** [comment]
Thank you!

**Pull request merged**
