### PR TITLE
Update to v0.8.8

### PR DESCRIPTION
**Pull request by felixtriller**

### CODE REVIEW

**Comment by WaKeMaTTa** [comment]
@felixtriller :clap: :clap: :clap:

**Comment by felixtriller** [comment]
I sneaked in lite and bs4 styles and javascript.

**Comment by kamnog** [comment]
hello, whats the status?

**Comment by WaKeMaTTa** [comment]
ping/ @luciuschoi @hackerwins

**Comment by felixtriller** [comment]
Merge me baby!

**Comment by luciuschoi** [comment]
Thank you for your devotion.

**Pull request merged**
